[package]
name = "qr-ip"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
image = "0.25.2"
show-image = "0.14"
qrcode = "0.14.1"
local-ip-address = "0.6.5"
